# Generated by Django 5.0.4 on 2024-05-06 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Info',
            new_name='ContactInfo',
        ),
        migrations.RenameModel(
            old_name='Job_Seeker',
            new_name='JobSeeker',
        ),
    ]
