# Generated by Django 5.0.4 on 2024-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contact_info_contactinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='files',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
