# Generated by Django 5.0.4 on 2024-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_jobseeker_bio_alter_jobseeker_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(choices=[('Iceland', 'Iceland'), ('Denmark', 'Denmark'), ('England', 'England'), ('United States', 'United States'), ('Bolivia', 'Bolivia')]),
        ),
    ]
