# Generated by Django 5.0.4 on 2024-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contactinfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='files',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_nr',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_nr',
            field=models.CharField(default='1234567', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default_profile_img.png', upload_to=''),
        ),
    ]
