# Generated by Django 5.0.4 on 2024-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_img'),
    ]

    operations = [
    ]
