# Generated by Django 5.0.4 on 2024-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_jobseeker_files_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='full_name',
            field=models.CharField(max_length=80, blank=True),
        ),
    ]
