# Generated by Django 5.0.4 on 2024-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_jobseeker_files_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_nr',
            field=models.CharField(max_length=100, blank=True),
        ),
    ]
