# Generated by Django 5.0.4 on 2024-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_jobseeker_files_remove_profile_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='files',
            field=models.EmailField(max_length=100, blank=True),
        ),


        
    ]
