# Generated by Django 5.0.4 on 2024-05-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_jobseeker_files_remove_profile_time_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='files',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_posted',
        ),
    ]
