# Generated by Django 5.0.4 on 2024-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_jobseeker_files_remove_profile_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default_profile_img.png', upload_to='profile-images'),
        ),
    ]
