# Generated by Django 5.0.4 on 2024-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(choices=[('Iceland', 'Iceland'), ('Denmark', 'Denmark'), ('England', 'England'), ('United States', 'United States'), ('Bolivia', 'Bolivia')], default=''),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zip_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
