# Generated by Django 5.0.4 on 2024-05-06 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_Experience',
            new_name='WorkExperience',
        ),
    ]
