# Generated by Django 5.0.4 on 2024-05-07 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_joblisting_application_job_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reccomendation',
            new_name='Recommendation',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='reccomendations',
            new_name='recommendations',
        ),
    ]
