# Generated by Django 5.0.4 on 2024-05-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_reccomendation_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='listings.recommendation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='listings.workexperience'),
        ),
    ]
