# Generated by Django 5.0.4 on 2024-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_joblisting_category_alter_joblisting_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='work_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Summer job', 'Summer job')]),
        ),
    ]
