# Generated by Django 5.0.4 on 2024-05-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_joblisting_work_type'),
        ('users', '0004_alter_contactinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_information',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.contactinfo'),
        ),
    ]
