# Generated by Django 5.0.4 on 2024-05-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_application_contact_information'),
        ('users', '0004_alter_contactinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_information',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.contactinfo'),
        ),
    ]
