# Generated by Django 5.0.4 on 2024-05-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
