# Generated by Django 5.0.4 on 2024-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_joblisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending'),
        ),
    ]
