# Generated by Django 5.0.4 on 2024-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='international'),
        ),
    ]
