# Generated by Django 5.0.4 on 2024-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_joblisting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='International'),
        ),
    ]
