# Generated by Django 5.0.4 on 2024-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_application_job_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Biotechnology', 'Biotechnology'), ('Managing position', 'Managing position'), ('Cooking', 'Cooking'), ('Painting', 'Painting'), ('Arts', 'Arts'), ('Cinema', 'Cinema'), ('Social Media', 'Social Media'), ('Finance', 'Finance')]),
        ),
    ]
